### ISSUE TITLE
plugin.choria.network.peer_port is 5222 instead of 4223

### ISSUE THREAD

**Issue by zipkid** [choria-io/go-choria#1219]
As suggested by you

```
choria::server_config:
  plugin.choria.network.peer_port: 4223
```

**Comment by ripienaar** [comment]
Small correction, this is a choria::broker class parameter I was wrong on slack, I'll fix the defaults which I incorrectly changed in the last release

**Comment by ripienaar** [comment]
Hmm, turns out there is no behavior change, previously the default was also 5222

https://github.com/choria-io/go-choria/commit/2c3e169bce6e8e29387af9f234afd6b7775a32b9#diff-46f0b77781fc511924b0a47bf88592125a285faadbff745b543f7bce4c53aabdL51

So I am inclined to leave this as is, probably the docs need clarification instead.
