### ISSUE TITLE
create debian packages

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#151]

**Comment by ripienaar** [comment]
@mckern if you did feel like doing somthing how about some feedback on this pile of stackoverflow copy/paste driven packaging? https://github.com/ripienaar/go-choria/tree/151/packager/templates/ubuntu

I am sure its awful, i know nothing of debian.

Technically quite simple I guess - mainly i need the broker off everywhere by default, server on everywhere by default - restarted on update either one that runs during upgrade

**Comment by ripienaar** [comment]
The global dir will be copied into the xenial one during build process - when I add other ubuntu repos those will be shared between them

**Comment by mckern** [comment]
Initial thoughts are that the "most" Debian-is way to handle this is breaking the broker and the server into two separate packages -- Debian policy is to basically reduce everything to its smallest possible surface area across as many packages as it takes. YMMV, it only applies to anything that they distribute; but it's what "classic" Debian admins expect to see.

More specific suggestions & comments:

- typo in the `rules` file, line 9: `privileges`, not `priviledges`
- `rules`, line 51: I think with the `find` instance there, you can also use `-print0` instead of `-printf` and a formatting string -- no functional difference, just saves a few characters.

I haven't tried building anything with this -- have you produced packages with it? What I see looks pretty reasonable for a relatively abstracted Debian build.

**Comment by ripienaar** [comment]
@mckern thanks for that, yeah I am aware it'll be best to split it, same really on RHEL.

At first I did split it for rhel, I dont recall what the issue was perhaps my tooling was too weak and it was a hassle.  But this split business was always a headache for me with the mcollective/mcollective-common/mcollective-client packages, constant struggles so I avoided it.

Now I might split it into choria and choria-broker i guess but will have to see how it pans out, for sure its against debian policy to have services off by default as would be the case with broker.

Thanks for those points about the rules will check it out

It does make packages yes and they install fine i have not had a chance to test them properly for things like do they restart the services during upgrade etc, will get to that (dont have debian machines :P)

**Comment by ripienaar** [comment]
@mckern turns out this was actually a shit show, the various copy/pasting done from different guides was a mix of dh and non dh style packaging - and it didnt work particularly well

reworked it to be pure dh and now its better - though I cant get the systemd dh plugin going, I suspect xenial is just old, but whats there now works fine
